[package]
name = "reactor"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rootcause = "0.11.1"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "sync"] }
tower = "0.5.2"
